#!/bin/bash

echo "Run O2 detector simulation for given input file ${2}"
time=$(date)
echo "Start time : $time"

seed=1000
jobid=$SLURM_JOB_ID
seed=$((seed+jobid))

cd ${1}

echo "Processing ${3} events"

o2-sim --seed $seed -j 12 -n ${3} -m FV0 FT0 PIPE ITS -e TGeant3 -g extgen --extGenFile=/n/work00/heimarry/simO2/gengen.C --extGenFunc="gengen("\"${DETSIM_DIR}\/${2}\"")"

time=$(date)
echo "Transportation finished : $time"
echo "Start digitizer workflow"

o2-sim-digitizer-workflow -b --onlyDet=FV0,FT0

echo "Digitization finished"
echo "Clean cerenkov photons from kinetimatics file to reduce size"

root -b ${DETSIM_DIR}\/RemoveCkov.C
mkdir extrafiles
mv o2sim_HitsFV0.root extrafiles/o2sim_HitsFV0.root
#mv o2sim_HitsFT0.root extrafiles/o2sim_HitsFT0.root
mv output_nockov.root extrafiles/output_nockov.root
rm MCStepLogger* dpl-config.json gphysi.dat hitmerger-simdata* localhost* o2sim* primary-get* tpc_polya.root 

echo "Cerenkovs removed"
echo "Job is finished!"

